---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by matrocob.
--- DateTime: 07.06.2020 02:17
---
box.cfg{listen = 3301}
s = box.schema.space.create('tester')

s:format({
    { name = 'id', type = 'unsigned' },
    { name = 'band_name', type = 'string' },
    { name = 'year', type = 'unsigned' }
})

-- primary key
s:create_index('primary', {
    type = 'hash',
    parts = { 'id' }
})

s:insert { 1, 'Roxette', 1986 }
s:insert { 2, 'Scorpions', 2015 }
s:insert { 3, 'Ace of Base', 1993 }

s:select { 3 }

-- second key
s:create_index('secondary', {
    type = 'hash',
    parts = { 'band_name' }
})

-- drop index
s.index.secondary:drop()
